### ISSUE TITLE
[제안] 선택한 인증서가 만료된 경우 알리는 기능

### ISSUE THREAD

**Issue by hided62** [yourtablecloth/TableCloth#106]
**제안해주시는 기능이 소프트웨어로 인해 발생한 문제 때문인가요? 그렇다면 자세히 알려주세요.**

`D:\NPKI`에 인증서를 두고 사용하는 방식을 사용하고 있습니다. 공동 인증서 선택 시에는 '이동형 디스크'를 선택하면 되구요.

식탁보에서는 '직접 공동 인증서 찾기...' 버튼을 이용하여 가져올 수 있는데, 제가 선택한 인증서가 이미 만료된 것이었음을 확인했습니다. 그러다보니 실제 샌드박스 내에서는 인증서가 나타나지 않았구요.

**어떻게 개선한다면 좋을까요?**
'직접 공동 인증서 찾기...'로 찾은 인증서가 만료되었는지 한번 확인하는 절차가 있으면 좋을 것 같습니다.

이미 만료된 것으로 나온다면, 경고 메시지를 한번 띄워주는거죠.

'이미 만료되었습니다'가 떠야할지, '만료된 인증서이므로 인증이 되지 않을 수 있습니다. 그래도 진행하시겠습니까?'가 떠야할지는 잘 모르겠습니다.

**다른 대안이 있을까요?**
새로운 인증서를 알아서 찾아줄 순 없으니, 경고 메시지면 충분할 것 같습니다.

**추가 맥락**
`D:\NPKI`가 아니라 원래의 `AppData/LocalLow/NPKI`에서도 인증서 만료 여부를 확인하나요...?

**Comment by rkttu** [comment]
0.5.7 버전에 개선 사항을 반영하여 출시할 예정입니다!
