### ISSUE TITLE
[버그] 원격 웹사이트로부터 Catalog.xml 파일을 불러올 수 없이 설치를 계속 진행할 수 없습니다.

### ISSUE THREAD

**Issue by jiggol** [yourtablecloth/TableCloth#107]
**버그에 대한 설명**
식탁보를 실행하고 샌드박스 실행을 누르면 아래 메시지내용의 오류 대화상자가 출력 됩니다.

_원격 웹사이트로부터 Catalog.xml 파일을 불러올 수 없이 설치를 계속 진행할 수 없습니다. 참고로, 발생했던 오류는 다음과 같습니다. - the remote name could not be resolved: 'yourtablecloth.github.io'_

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. 식탁보 실행
2. 샌드박스 실행 버튼 클릭

**동영상 또는 스크린샷**
![식탁보 오류화면](https://user-images.githubusercontent.com/9375500/204843603-201c1930-8925-425f-bd25-9e82533351d0.jpg)

**시스템 사양**
 - OS: Windows11 버전 22H2 (빌드 22621.819)
 - CPU 아키텍처: AMD Ryzen 5800X
 - 브라우저: Microsoft Edge (Version : 106.0.1370.34 64bit)
 - 소프트웨어 릴리스 버전: 0.5.5.0

**참고 사항**
샌드박스가 실행 되고 나서 오류화면이 나오는 시점에 샌드박스 내의 윈도우 화면의 우측 하단에 네트워크 연결 아이콘을 보면 연결이 안된 것으로 나옵니다. 아마 제가 생각하건데 식탁보에서 샌드박스실행 버튼을 누르고 실행이 되고 Catalog.xml 파일을 다운로드 하려는 시점에 인터넷이 연결되지 않아 발생하는 문제 아닐까 하는 추측을 해 봅니다.

샌드박스가 실행되고 나서 조금 있으면 인터넷 아이콘이 연결된 것으로 바뀌거든요. Catalog.xml  파일 다운로드 전에 약간의 지연시간을 주거나 인터넷 연결 체크를 해서 연결되면 다운로드가 되게끔 한다던지 하면 좋을 것 같습니다.

**Comment by rkttu** [comment]
건의해주신대로 retry logic을 추가하여 0.5.6 버전에 출시할 예정입니다.
