### ISSUE TITLE
[버그] MS Edge 실행 불가

### ISSUE THREAD

**Issue by ensup** [yourtablecloth/TableCloth#114]
**버그에 대한 설명**
MS Edge 브라우저 실행이 안됩니다

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. KB 국민은행 선택 후 실행
2. Edge 아이콘 클릭
3. 이후 오류가 뜨면서 실행 안됨

**동영상 또는 스크린샷**
![no-edge](https://user-images.githubusercontent.com/38882082/222949490-182bc1e9-d275-49a5-8ebb-f4c66a4371a5.png)

**시스템 사양**
 - OS: Windows 11 EDU 22H2 (22621.1344)
 - CPU 아키텍처: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz   2.50 GHz
 - 브라우저: Edge
 - 소프트웨어 릴리스 버전: v0.5.5

**참고 사항**
Windows 클린 설치 후 Edge가 없던데 업데이트 되면서 edge가 기본 설치에서 빠졌을 수도 있을 것 같습니다.

**Comment by rkttu** [comment]
#114 이슈와 병합하여 다룰 예정입니다.
