### ISSUE TITLE
[버그] 홈택스에서 공동인증서가 표시되지 않음

### ISSUE THREAD

**Issue by dadammall** [yourtablecloth/TableCloth#118]
**버그에 대한 설명**
알기 쉽고 간결하게 발생하는 버그에 대한 내용을 알려주시면 감사하겠습니다.

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. 홈텍스를 식탁보 프로그램으로 실행시에 공동인증서 창에서 프로그램이 미설치 됐다고 나오면서 인증서 기능이 동작하지  않습니다.
2. ...

**기대하는 동작**
1. 다른 사이트들처럼 하드웨어 저장소가 활성화 되야 하며 인증서를 가져야와야 합니다. 

**동영상 또는 스크린샷**
![image](https://github.com/yourtablecloth/TableCloth/assets/131240466/ef0418e1-fe94-4e70-a0fb-211d701489dc)

**시스템 사양**
 - OS: window11 pro
 - CPU 아키텍처: intel 12th
 - 브라우저: edge
 - 소프트웨어 릴리스 버전: 0.5.5.0

**참고 사항**
문제에 관련된 다른 언급할 사항이 있으면 기재해주시면 감사하겠습니다.

**Comment by rkttu** [comment]
확인해본 결과 MagicLine4NX가 자동으로 시작되어야 웹 프론트엔드에서 하드 디스크에 설치된 로컬 인증서를 검색할 수 있는데, 홈택스 측 사이트에서 구동 코드가 누락된 것 같이 보입니다. 제가 확인해봤을 때는 수동으로 `C:\Program Files (x86)\DreamSecurity\MagicLine4NX\MagicLine4NX.exe` 프로그램을 시작하면 계속 설치하라는 메시지는 더 이상 나타나지는 않습니다.

이와는 별개로 Internet Explorer 모드를 홈택스에서 더 이상 사용하지 않도록 호환성 모드 목록에서 사이트를 제거하고, Veraport 확장 프로그램을 설치하도록 카탈로그를 업데이트해두었습니다.
