### ISSUE TITLE
[버그] 윈도우 11에서 파일탐색기가 안열림

### ISSUE THREAD

**Issue by sinarang** [yourtablecloth/TableCloth#141]
**버그에 대한 설명**
윈도우 11에서 샌드박스 관련 파일탐색기 오류가 있음

.

**재현 방법**
윈도우 11에서 샌드박스 실행후 파일탐색기 실행시 열리지 않음

**기대하는 동작**
파일탐색기가 열려야함 

**동영상 또는 스크린샷**
버그가 발생하기까지의 과정을 설명하는 동영상이나 스크린샷을 가능한 경우 첨부해주세요.

**시스템 사양**
 - OS:
 - CPU 아키텍처:
 - 브라우저:
 - 소프트웨어 릴리스 버전:

**참고 사항**

-해결방법

wsb파일에서 configuration 부분에 다음과 같이 추가하면 해결됨

<Configuration>
  <MappedFolders>
    <MappedFolder>
      <HostFolder>C:\Windows\SystemApps\Microsoft.WindowsAppRuntime.CBS_8wekyb3d8bbwe</HostFolder>
      <SandboxFolder>C:\Windows\SystemApps\Microsoft.WindowsAppRuntime.CBS_8wekyb3d8bbwe</SandboxFolder>
      <ReadOnly>true</ReadOnly>
    </MappedFolder>
  </MappedFolders>
</Configuration>

참고 : https://answers.microsoft.com/en-us/windows/forum/all/windows-11-sandbox-does-not-open-file-explorer/bd04adf1-cbd1-4674-b224-9560b4cbecae

**Comment by SalaryTheft** [comment]
최신 Windows 누적 업데이트에서 수정되었습니다.
KB5032288(OS 빌드 22631.2792)

**Comment by rkttu** [comment]
식탁보 프로젝트 자체의 문제가 아닌 Windows OS 상의 문제이며, 동시에 최신 버전의 Windows 업데이트 적용으로 해결될 수 있는 문제로 판단하여 이슈를 닫습니다.
