### ISSUE TITLE
[버그] 현대해상 접속시 소프트웨어 설치할 때 404 not found가 발생합니다.

### ISSUE THREAD

**Issue by CaritasPostech** [yourtablecloth/TableCloth#145]
해당 부분 확인 요청드립니다.

**Comment by rkttu** [comment]
안녕하세요. 특정 사이트 접속 시 리소스를 다운로드받지 못하는 부분은 https://github.com/yourtablecloth/TableClothCatalog 쪽에 이슈를 올려주시거나, PR을 보내주시면 검토 후 반영하도록 하겠습니다. 일단 이 이슈는 닫고, TableClothCatalog 쪽에 이슈를 올려두겠습니다.

**Comment by CaritasPostech** [comment]
도움 주셔서 감사합니다!
