### ISSUE TITLE
[버그] 바로가기 에러

### ISSUE THREAD

**Issue by solworks77** [yourtablecloth/TableCloth#149]
**버그에 대한 설명**
알기 쉽고 간결하게 발생하는 버그에 대한 내용을 알려주시면 감사하겠습니다.
![스크린샷 2023-12-31 001309](https://github.com/yourtablecloth/TableCloth/assets/155246023/23dfc936-a41f-4bdd-b639-714c853c2a70)

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. ...바로가기 에러
2. ...

**기대하는 동작**
버그가 발생하지 않았다면, 원래 어떻게 동작해야 하는지 간단하고 명확하게 알려주세요.

**동영상 또는 스크린샷**
버그가 발생하기까지의 과정을 설명하는 동영상이나 스크린샷을 가능한 경우 첨부해주세요.

**시스템 사양**
 - OS:
 - CPU 아키텍처:
 - 브라우저:
 - 소프트웨어 릴리스 버전:

**참고 사항**
문제에 관련된 다른 언급할 사항이 있으면 기재해주시면 감사하겠습니다.

**Comment by rkttu** [comment]
혹시 별도의 안티바이러스 소프트웨어나 MDM 정책을 적용하고 계신지 확인해주시면 감사하겠습니다.

**Comment by rkttu** [comment]
이 이슈의 원인으로 예상되는 점을 수정 사항을 최근 릴리즈 1.12.1에서 반영했습니다. 최신 버전으로 업데이트한 후에도 문제가 발생할 경우 다시 제보 부탁드립니다.
