### ISSUE TITLE
[버그] 윈도우 샌드박스 초기화 실패

### ISSUE THREAD

**Issue by JamminKR** [yourtablecloth/TableCloth#150]
**버그에 대한 설명**
Windows 샌드박스를 초기화 하지 못했다고 합니다.

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. 식탁보 앱 실행
2. 필요한 업체 선택 후 실행하기
3. Windows 샌드박스를 초기화 하지 못했습니다. 오류 표출

**기대하는 동작**
음.. 샌드박스가 실행되야겠죠?

**동영상 또는 스크린샷**
![image](https://github.com/yourtablecloth/TableCloth/assets/155293694/61e57cca-2f66-4f17-8a9b-553a3af63ff7)

**시스템 사양**
 - OS: Windows 10 Home
 - CPU 아키텍처: AMD64
 - 브라우저: Chrome
 - 소프트웨어 릴리스 버전: 1.9.1.0

**참고 사항**
문제에 관련된 다른 언급할 사항이 있으면 기재해주시면 감사하겠습니다.

**Comment by rkttu** [comment]
Windows Sandbox 초기화 문제는 식탁보 프로젝트의 코드 수정으로는 해결이 불가합니다. 죄송하지만, 가능한 구체적인 정보가 더 있어야 보완을 검토하거나, 가이드를 작성할 수 있을 것 같습니다. 자세한 정보를 주실 수 있다면 댓글로 추가 답변 부탁드리겠습니다.

**Comment by gtuf** [comment]
안녕하세요 주인장님. 저 이슈랑 동일한 상황인데 우선 Window 10 Home은 샌드박스 지원이 되지 않아 강제로 코드를 실행시켜 설치까지는 진행했습니다. 그 후 식탁보를 실행하면 켜지긴 하는데 켜지기 전 팝업창으로 지원이 안되는 환경일 수도 있다고 나옵니다.

그 후 은행 실행 시 위와 같은 에러가 발생합니다. 별 다른 에러는 나오지 않아 추가적으로 말씀 드리기 어려울 것 같아요.

**Comment by gtuf** [comment]
![캡처](https://github.com/yourtablecloth/TableCloth/assets/16081652/7dc20a41-c99e-4c26-ba5e-ea01aa6d732f)

**Comment by JamminKR** [comment]
맞아요 저도 강제설치 -> 지원되지 않는 환경이용중 -> this error 이런순으로 가더라고요

**Comment by rkttu** [comment]
이슈에 대한 구체적인 정보가 부족한 관계로 해결이 어려워서 이슈를 닫습니다. 아울러, Windows 10 Home은 Windows Sandbox가 지원되는 버전이 아니어서 식탁보를 사용할 수 없습니다.
