### ISSUE TITLE
[버그] 우체국 인터넷 뱅킹 실행이 안됨

### ISSUE THREAD

**Issue by woohyukJo** [yourtablecloth/TableCloth#151]
**버그에 대한 설명**
알기 쉽고 간결하게 발생하는 버그에 대한 내용을 알려주시면 감사하겠습니다.
우체국 접속 시도 시에 모든 설치프로그램들이 설치 실패합니다.
**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. 식탁보를 실행해 우체국으로 들어갑니다. (옵션은 기본 옵션에서 건드리지 않았습니다)
2. 식탁보 자동 설치 프로그램이 프로그램 설치에 실패합니다.

**기대하는 동작**
veraport, Anysign, TouchEnkey64, NOS가 설치되어야 합니다. 

**동영상 또는 스크린샷**
![우체국설치실패](https://github.com/yourtablecloth/TableCloth/assets/68226384/fe0ce8f3-2eb6-43f2-8879-e3898bedea43)

**시스템 사양**
 - OS: Windows 10 Edu
 - CPU 아키텍처:x86(라이젠 1500x)
 - 브라우저:엣지(익스플로러 호환성 on)
 - 소프트웨어 릴리스 버전:1.9.1

**참고 사항**
문제에 관련된 다른 언급할 사항이 있으면 기재해주시면 감사하겠습니다.

**Comment by rkttu** [comment]
카탈로그를 최신화했습니다. 새로운 이슈가 발견될 경우 업데이트 부탁드리겠습니다.
