### ISSUE TITLE
[버그] 응답없음 상태 지속

### ISSUE THREAD

**Issue by Ktaewon** [yourtablecloth/TableCloth#154]
**버그에 대한 설명**
식탁보 프로그램 실행 후, 하나의 사이트를 들어갈 때 5분 이상의 로딩이 발생하며 그동안 앱은 응답없음 상태가 됩니다.

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. 식탁보 프로그램 실행 후, 하나의 사이트(예를 들어 농협은행)를 클릭
2. 식탁보 프로그램에서 해당 사이트 상세 내용(옵션) 나올 때 까지 5분 이상의 응답없음 상태 지속
3. 응답없음 상태 해제 시 상세 내용(옵션) 페이지로 이동 및 샌드박스 정상 실행 가능

**기대하는 동작**
긴 시간의 응답없음 발생하지 않아야 함.

**동영상 또는 스크린샷**
![image](https://github.com/yourtablecloth/TableCloth/assets/33050476/4c0f8b65-da89-4d96-bdaa-872d36b263e6)

**시스템 사양**
 - OS:윈도우 11 pro x64
 - CPU 아키텍처: x86(라이젠 5600)
 - 브라우저:Microsoft Edge
 - 소프트웨어 릴리스 버전:1.9.1

**참고 사항**
응답 없음이 풀린 후엔 모든 동작이 순조롭게 진행됩니다. 다만 다시 뒤로 가기 후 새로운 사이트를 누르면 동일하게 응닶없음 현상이 발생합니다.

**Comment by rkttu** [comment]
이 이슈의 원인으로 예상되는 점을 수정 사항을 최근 릴리즈 1.12.1에서 반영했습니다. 최신 버전으로 업데이트한 후에도 문제가 발생할 경우 다시 제보 부탁드립니다.
