### ISSUE TITLE
[버그] 파일과 연결된 앱이 없다고 나옵니다 해결 부탁드립니다.

### ISSUE THREAD

**Issue by Y-SAN2** [yourtablecloth/TableCloth#156]
실행하기를 누르면 
![제목 없음](https://github.com/yourtablecloth/TableCloth/assets/155983259/92075f96-e167-475e-8df5-2e5409483c6e)

이런화면이 뜨면서 실행이안됩니다 해결부탁드립니다..!

**버그에 대한 설명**
알기 쉽고 간결하게 발생하는 버그에 대한 내용을 알려주시면 감사하겠습니다.

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. ... 국세청 홈텍스 실행하기 버튼 클릭
2. ...

**기대하는 동작**
버그가 발생하지 않았다면, 원래 어떻게 동작해야 하는지 간단하고 명확하게 알려주세요.

**동영상 또는 스크린샷**
버그가 발생하기까지의 과정을 설명하는 동영상이나 스크린샷을 가능한 경우 첨부해주세요.

**시스템 사양**
 - OS: 
 - CPU 아키텍처:
 - 브라우저:
 - 소프트웨어 릴리스 버전:

**참고 사항**
문제에 관련된 다른 언급할 사항이 있으면 기재해주시면 감사하겠습니다.

**Comment by rkttu** [comment]
이 이슈가 발생하는 현상을 완화하기 위한 보완 코드를 곧 출시할 1.10.0.1 버전에서 적용할 예정입니다. 그러나 이와 별개로, 시스템 구성 상의 문제가 원인으로 보이는 문제로 생각됩니다.

혹시 이 증상을 경험하고 계신 분들 가운데에서 아래 명령어를 실행한 결과를 이 이슈의 댓글란에 스크립트 실행 결과를 알려줄 수 있는 분이 계시면 댓글을 남겨주시면 감사하겠습니다.

```
powershell -Command Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/yourtablecloth/TableCloth/main/tools/diagnose_wsb_association.ps1'))
```

고맙습니다.

**Comment by rkttu** [comment]
이 이슈의 원인으로 예상되는 점을 수정 사항을 최근 릴리즈 1.12.1에서 반영했습니다. 최신 버전으로 업데이트한 후에도 문제가 발생할 경우 다시 제보 부탁드립니다.
