### ISSUE TITLE
[제안] 복합실행 기능

### ISSUE THREAD

**Issue by glittery11** [yourtablecloth/TableCloth#158]
**제안해주시는 기능이 소프트웨어로 인해 발생한 문제 때문인가요? 그렇다면 자세히 알려주세요.**
한번에 한가지 사이트에 대한 세팅만 가능하다는 점입니다.
관공서 사이트, 은행 등 최소 2가지 이상의 사이트를 이용해야 하는 경우가 많습니다.

**어떻게 개선한다면 좋을까요?**
여러 사이트를 복합실행모드를 켜서 클릭하거나 Ctrl클릭 등으로 동시에 선택한 뒤, 해당 사이트들에 들어가는 세팅이 동시에 적용되도록 하면 좋을것 같습니다.

**다른 대안이 있을까요?**
실행중인 샌드박스에 다른 세팅을 밀어넣는다던가 하는 기능은..안되겠죠? 이외엔 떠오르는게 없습니다.

**추가 맥락**
뭐 더 드릴말씀은 없고,, 지금 프로그램도 너무 좋습니다. 이런걸 만들어주셔서 감사합니다

**Comment by rkttu** [comment]
#173 이슈로 병합하고자 합니다.
