### ISSUE TITLE
[버그] 윈도우10 홈에디션 샌드박스 기능지원버전 운영체제 질문드립니다...!

### ISSUE THREAD

**Issue by ant5033** [yourtablecloth/TableCloth#162]
버그는 아닙니다만 공홈에 질문이나 디스코드방등이 보이지 않아서 깃헙에 질문합니다 죄송해요

윈도우10 홈에디션이라 샌드박스기능이 없어 별도로 설치후
실행하니 

<img width="233" alt="image" src="https://github.com/yourtablecloth/TableCloth/assets/80405495/4fd7cf33-6768-42fd-9514-25b28ee9f57c">

해당 문구가 뜨는데 사용하는데에는 지장이 없는건가요 ?

**Comment by rkttu** [comment]
안녕하세요. 자주 묻는 질문에 대한 답변으로 소개드린 내용을 참고해주시면 감사하겠습니다.

https://github.com/yourtablecloth/TableCloth/discussions/159
