### ISSUE TITLE
[Short/Mid Term Project] (가칭) 온라인 서비스 자동 설치 도구

### ISSUE THREAD

**Issue by rkttu** [yourtablecloth/TableCloth#173]
Windows Sandbox가 없어서 식탁보를 사용하지 못해서 아쉽다는 피드백을 조금 다르게 생각해봤습니다.

현재 Hostess라는 식탁보와 함께 배포되는 자동 설치 도구가 있는데, 이 도구의 스핀오프 버전으로 가칭 "온라인 서비스 자동 설치 도구"를 구상해보고 있습니다.

- 권장 환경: 별도 가상 컴퓨터 또는 전용 목적의 컴퓨터에서 실행합니다.
  - 예시 1: 주로 사용하는 노트북 PC 외에 집에서 사용하는 데스크톱 PC
  - 예시 2: Parallels나 Hyper-V를 이용하여 만든 가상 PC
  - 예시 3: 식탁보를 통하지 않고 실행한 Windows Sandbox 안에서 직접 구동 - 또는 - 식탁보 프로그램의 확장 기능으로 사용
- 배경
  - 별도의 가상 컴퓨터나 전용 목적의 컴퓨터를 운영하는 경우 인터넷 뱅킹, 공공 온라인 서비스 등이 요구로 하는 플러그인 설치를 무인 설치 모드로 한 번에 돌려서 설치 과정을 가속/간소화 합니다.
  - 보안 플러그인을 자동으로 설치하고 띄우는 용도로 컴퓨터를 최적화합니다.
- 아키텍처
  - 식탁보와 동일한 카탈로그를 공유합니다. (https://github.com/yourtablecloth/TableClothCatalog/blob/main/docs/Catalog.xml)
- 프로그램 제거
  - 이 프로그램은 자동 설치 기능만 제공하며, 자동 제거 기능은 제공하지 않습니다.
  - 프로그램 설치 제거는 사용자의 의지와 선호도에 따라 직접 방법을 결정할 수 있습니다.

관련 이슈: #158, #153

**Comment by jaepil-choi** [comment]
이거 너무 좋은거같고 반드시 식탁보가 지향해야 할 방향이라 생각합니다. 

식탁보를 쓰는 목적은 내 컴에 더러운 정크 소프트웨어들을 안깔고 싶어서이지, 용량을 아끼고자 하는 것도 아니며 오히려 매번 다시 설치하는데 드는 시간 비용이 식탁보의 아쉬운 점입니다. 

쉽지만은 않을 것 같은게: 

- Hyper-V의 경우 윈도우 설치하려면 진짜 윈도우 여분이 1개 필요한 것으로 알고 있는데, 이게 큰 걸림돌이 되지는 않을까요? 
- Hyper-V 처럼 한 번 만들고 오래 뒤에 다시 켜는 경우 Outdated 되는 경우가 많은 것 같습니다. 
    - 샌드박스는 매번 새로 켜져서 가장 최신의 버전들을 받고 (변화에 대응), 개발자님도 카탈로그를 계속 유지관리 해주시며 최신을 유지해주시기에 원활하게 식탁보가 돌아가고 있지만 
    - 개인별로 Hyper-V를 필요할때만 켠다면 그게 잘 안되겠죠... 이 부분이 또 하나의 넘어야 할 산이라 생각합니다. 
- (아이디어가 있는데 말이 되는지는 모르겠음) 어차피 기왕에 기관별 설치해야할 최신 카탈로그를 유지한다면, 차라리 이게 다 설치된 상태를 스냅샷처럼 찍든지 (맥 타임머신같은 느낌 / 윈도우 이미지백업같은 느낌) 해서 샌드박스를 쓰되 한 방에 설치되게 하는 절충안도 가능하지 않을까요?
