### ISSUE TITLE
[버그] 식탁보에서 Windows Sandbox 실행을 하면 프로그램이 멈춥니다.

### ISSUE THREAD

**Issue by sleeping-player** [yourtablecloth/TableCloth#174]
**버그에 대한 설명**
식탁보 앱 실행 후 아무 은행 등을 고른 뒤 실행하기를 누르면 식탁보 앱이 응답 없음 상태로 뻗고 윈도 샌드박스는 실행되지 않습니다.

**재현 방법**
상술하였습니다.
인증서를 교체도 해봤으며, 새로운 사용자 인터페이스 사용여부도 변경해봤습니다.
명령줄 복사하기를 통해 실행해도 명령줄이 식탁보 앱을 실행한 후 식탁보 앱이 뻗습니다.
(식탁보앱을 경유하지 않는 해결책일줄 알았는데, 그게 아니었던 모양입니다.)

**기대하는 동작**
그저 정상 실행

**동영상 또는 스크린샷**

**시스템 사양**
 - OS: Windows 10 Pro 22H2 19045.3996
 - CPU 아키텍처: Intel(R) Core(TM) i5-6400T CPU
 - 브라우저: 주로 msedge chromium
 - 소프트웨어 릴리스 버전: 1.12.1 및 1.12.0입니다. 이 문제는 1.9.1에서는 없었습니다.

**참고 사항**
로그 첨부 방법이 있나 모르겠네요. 식탁보 매뉴얼 같은 곳에 로그 어디 있는지 안써있네요..

**Comment by sleeping-player** [comment]
기다려봤더니 #154 이슈에서처럼 윈도 샌드박스가 실행이 되는 것이 확인되었습니다.
지금 당장 수정하지 못해 죄송합니다만 그렇다면 본질적으로 #154 에 합쳐야 한다는 얘기겠습니다..

> 문제 분석을 좀 더 심층적으로 해봐야 할 것 같습니다. 응답 없음 상태로 빠지는 것이 재현되면, 프로그램을 그냥 종료하지 마시고, https://kr.bandisoft.com/kb/dump/ 에 나와있는 방법에 따라 식탁보 (TableCloth) 프로세스의 메모리를 덤프해서 만들어진 DMP 파일을 rkttu at rkttu.com 으로 메일을 보내주실 수 있을지 문의드립니다.

일단 덤프를 시도해보겠습니다. 메일 지금 보내는 중입니다.

**Comment by rkttu** [comment]
@sleeping-player 보내주신 메모리 덤프 파일을 토대로 문제가 되는 것으로 예상되는 부분을 수정한 빌드를 올렸습니다. 기존 버전을 제거하고 아래 MSI 파일을 새로 설치하여 문제가 재현되는지 살펴봐주시면 감사하겠습니다.!

https://github.com/yourtablecloth/TableCloth/actions/runs/7693533162/artifacts/1201837589

**Comment by sleeping-player** [comment]
안좋습니다.
실행하기 버튼 누르면 아무 동작이 없네요...
죽지도 않고 실행되지도 않고
버튼이 그냥 장식이 됐습니다.

**Comment by rkttu** [comment]
보내주신 메모리 덤프 파일을 분석해보면, 식탁보 안에서 실행될 자동 설치 프로그램의 ZIP 파일을 임시 디렉터리로 압축 해제하는 과정에서 프로그램이 멈추는 현상으로 추정됩니다.

언급해주신 #154는 샌드박스 실행 버튼을 누른 후가 아닌, 세부 항목 페이지로 들어갈 때 발생하는 멈춤 현상으로 지금 제보해주신 것과는 다른 문제라고 생각합니다.

제가 전업으로 식탁보 개발을 진행하고 있는 것은 아니기 때문에 이 이슈를 집중해서 계속 살펴볼 수는 없습니다. 그러나 시간이 좀 걸릴 수 있겠습니다만, 압축 파일 해제와 같은 디스크에 파일을 쓰는 동작과 관련된 개선 사항들을 1.9.1 버전 때의 파일 시스템 입출력 코드로 원상 복귀하여 문제 재현 여부를 확인해보려 합니다.

이에 따라 새 빌드를 다시 한 번 공유드릴 예정입니다. 해당 빌드에서 문제가 해결이 되는지 다시 한 번 살펴봐주시면 감사하겠습니다.

**Comment by rkttu** [comment]
@sleeping-player 문제 해결에 계속해서 도움 주셔서 고맙습니다. 기존 프로그램을 제거한 후, 아래 버전으로 교체 설치한 후에도 같은 증상이 계속 발생하는지 확인해주시면 감사하겠습니다. 🙏 

https://github.com/yourtablecloth/TableCloth/actions/runs/7737017684/artifacts/1211156931

**Comment by sleeping-player** [comment]
> @sleeping-player 문제 해결에 계속해서 도움 주셔서 고맙습니다. 기존 프로그램을 제거한 후, 아래 버전으로 교체 설치한 후에도 같은 증상이 계속 발생하는지 확인해주시면 감사하겠습니다. 🙏
> 
> https://github.com/yourtablecloth/TableCloth/actions/runs/7737017684/artifacts/1211156931

해당 상황 발생하는 곳에 내일 9시 반까지는 가보지 못해서 좀 늦으니 양해 부탁드립니다.

**Comment by sleeping-player** [comment]
> > @sleeping-player 문제 해결에 계속해서 도움 주셔서 고맙습니다. 기존 프로그램을 제거한 후, 아래 버전으로 교체 설치한 후에도 같은 증상이 계속 발생하는지 확인해주시면 감사하겠습니다. 🙏
> > https://github.com/yourtablecloth/TableCloth/actions/runs/7737017684/artifacts/1211156931
> 
> 해당 상황 발생하는 곳에 내일 9시 반까지는 가보지 못해서 좀 늦으니 양해 부탁드립니다.

일이 바빠서 테스트를 제때 못해서 죄송합니다.
방금 해봤더니 정상 범위의 시간 내에 샌드박스 실행 됩니다.

**Comment by rkttu** [comment]
@sleeping-player 아닙니다. 덕분에 발견하기 어려울 뻔한 문제를 잘 해결할 수 있었습니다. 다음주 초까지 문제를 수정한 새 빌드를 업데이트하겠습니다. 고맙습니다! 🙇
