### ISSUE TITLE
[버그] anysign 버전 업 (msafer)

### ISSUE THREAD

**Issue by crucifyer** [yourtablecloth/TableCloth#189]
https://www.msafer.or.kr/AnySign4PC_info/install/v1.1.3.3/AnySign_Installer.exe

식탁보가 설치 했는데, 이걸로 다시 설치하라고 나오네요.

**Comment by rkttu** [comment]
특정 웹 사이트에서 사용하는 컴포넌트에 관한 제보는 이 리포지터리가 아닌 https://github.com/yourtablecloth/TableClothCatalog 리포지터리로 제보 부탁드립니다. 또한, 어떤 웹 사이트에서 발생한 문제인지도 언급해주셔야 합니다.
