### ISSUE TITLE
[제안] 인증서 지문값을 확인하여 마지막으로 선택한 공동 인증서 자동으로 찾기

### ISSUE THREAD

**Issue by rkttu** [yourtablecloth/TableCloth#190]
맥락: https://github.com/yourtablecloth/TableCloth/discussions/186#discussioncomment-8714751

- 만료된 인증서만 따로 모아서 아래쪽으로 정렬되도록 보여주면 좋겠습니다.
- 마지막으로 사용한 인증서 지문값을 확인하여 공동 인증서를 자동으로 선택하는 기능을 넣는다면 좋겠습니다.
- 공인인증서 선택 스크롤박스 높이를 좀 더 키워서 보여주면 좋겠습니다. (중간 아래쪽에 여백이 많습니다.)

**Comment by gwakhuiwon** [comment]
요청드린 부분 검토해주셔서 감사합니다

추가적으로 인증서 선택 팝업창에서
1. 만료된 인증서는 아래쪽으로 정렬되도록
2. 공인인증서 선택 스크롤박스 높이를 좀 더 키우기 (중간 아래쪽에 여백이 많네요)

건의 드립니다^^
