### ISSUE TITLE
명령줄 인수 처리기 코드 리팩토링

### ISSUE THREAD

**Issue by rkttu-mzc** [yourtablecloth/TableCloth#198]
현재 명령줄 인수 처리기 코드가 매우 유지보수하기 어렵게 되어있다. 커맨드라인 파서 라이브러리들이 좋은게 많이 있으니 적절한 것을 하나 택해서 TableCloth와 Spork/Hostess에 모두 적용해봐야 할 것이다.

**Comment by rkttu** [comment]
System.CommandLine을 구현체로 사용하기로 결정하면서, 바로 가기 생성과 관련된 제약 사항을 해소하기 위한 방안을 같이 찾을 수 있을 것으로 고려함. RSP (Response File, 응답 파일)을 문법적으로 지원하므로, 식탁보 호출에 필요한 인자 구성을 CreateProcessA/W에 전달하는 명령줄 문자열 대신 RSP 파일로 wrapping하도록 바로 가기 생성 형태를 같이 바꾸면 어떨지 고민해봐야 할 것.
