### ISSUE TITLE
구성 파일이 잘못되었습니다 오류

### ISSUE THREAD

**Issue by riemannulus** [yourtablecloth/TableCloth#20]
빌드: Preview v0.5.0
환경: Windows 11 x64 
![image](https://user-images.githubusercontent.com/16367497/130269251-fcde458a-5d2a-42a7-8f92-fda96de3aa70.png)

오류내용: NH농협은행 선택 후 `샌드박스 실행` 버튼 사용 시 '구성 파일이 잘못되었습니다' 라는 오류 팝업 발생.

![image](https://user-images.githubusercontent.com/16367497/130269104-a1f6058d-e654-46dc-976f-1b4297c3d179.png)

**Comment by rkttu** [comment]
`%localappdata%\TableCloth\` 폴더 아래에 가장 마지막에 만들어진 `bwsb_`로 시작하는 폴더 (개인 인증서 파일이 들어있는 `certs` 폴더 제외)를 압축해서 보내주시면 디버깅할 수 있을 것 같습니다.

**Comment by rkttu** [comment]
기존 버전을 삭제하고, 아래 버전을 설치해서 같은 방법으로 실행했을 때 어떻게 결과가 나타나는지 알고 싶습니다.
https://github.com/yourtablecloth/TableCloth/suites/3558777048/artifacts/85382936

**Comment by gdaegeun539** [comment]
동일 오류라 일단 여기에 커멘트 남겨봅니다.

빌드: Preview 0.5.0.0 및 5dec7cd(위 링크 버전)

오류 환경: Windows 10 21H1 x64
![Env_Preview](https://user-images.githubusercontent.com/41503781/130386527-749cc06e-d4ea-44f4-a091-d6e2e18e8409.png)

오류 내용: 위와 동일하지만 아무 옵션도 선택하지 않았을 때도 동일 오류 발생
![Err1](https://user-images.githubusercontent.com/41503781/130386265-423940a4-3313-4049-90ef-98faf54b1b26.png)

또한 `bwsb_` 폴더가 `%localappdata%\TableCloth\` 가 아닌 `C:\Users\user\AppData\Local\Packages\391c216c-bdb4-4fbf-ae4c-7a0d9de6e6ff_441rpnvtdm4r0\LocalCache\Local\TableCloth` 에 생성됨
![Path](https://user-images.githubusercontent.com/41503781/130386747-214d1515-97ac-47df-8e8f-ea924e81303d.png)

해당 폴더 압축하여 첨부합니다.
[0.5.0.0_bwsb.zip](https://github.com/yourtablecloth/TableCloth/files/7028980/0.5.0.0_bwsb.zip)
[5dec7cd_bwsb.zip](https://github.com/yourtablecloth/TableCloth/files/7028981/5dec7cd_bwsb.zip)

**Comment by rkttu** [comment]
@gdaegeun539 @riemannulus LocalAppData 디렉터리를 가져오는 기존 방법은 상황에 따라 %localappdata%\TableCloth가 아닌 가상화된 경로로 대체되는데, 이 때 경로가 %userprofile%\AppData\Local로만 반환되고 App Package ID를 포함한 뒷쪽 경로가 XML 파일에는 기록되지 않아 일관성없는 절대 경로가 들어가는 것 같습니다.

MSIX 패키징 방식을 사용하기로 결정했기 때문에, 이 부분은 정식 UWP API를 사용하는 것이 맞다고 판단하여 LocalAppData 디렉터리를 가져오는 방법을 수정한 빌드를 만들었는데, 혹시 문제가 해결되는지 여부를 봐주시면 감사하겠습니다.

테스트 빌드: https://github.com/yourtablecloth/TableCloth/suites/3576032249/artifacts/85950992

**Comment by gdaegeun539** [comment]
![Solved2](https://user-images.githubusercontent.com/41503781/130589463-1d4da41c-bdb2-4a3d-a3a8-06a65959bc59.png)
테스트 빌드 설치 후 실행해보니 해당 오류 해결되었습니다.

다만 사이트에 필요한 프로그램 자동 설치가 진행되지 않는 현상이 발생하네요. 다른 오류이니 일단은 다른 issue로 올리겠습니다.

**Comment by rkttu** [comment]
문제 해결을 위해 TargetFramework에 UWP 지원을 추가한 모니커를 사용한 후, #30 오류가 발생함. UWP 지원이 포함되면 기존에 사용하던 보안 모델이 훨씬 더 엄격하게 제한되어 식탁보에서 의도하는 동작이 막힘.

**Comment by rkttu** [comment]
@gdaegeun539 @riemannulus 안녕하세요. 0.5.1 버전을 업데이트하면서 MSIX 방식 대신 MSI 방식으로 패키징을 변경했습니다. 이전 방식은 실행 시 보안 제약이 강하게 걸려있어 제보해주신 문제가 나타나는것으로 보여 변경했습니다.

**Comment by rkttu** [comment]
https://github.com/yourtablecloth/TableCloth/issues/30#issuecomment-907761450 문제까지 같이 해결됨을 확인해주셔서 이 이슈는 닫습니다. 필요한 경우 다시 이슈를 오픈해주시면 감사하겠습니다.
