### ISSUE TITLE
[버그] 1.12버전 이후 모든 식탁보 프로젝트가 세부 설정을 유지하지 못합니다.

### ISSUE THREAD

**Issue by b1uebeach** [yourtablecloth/TableCloth#200]
https://github.com/yourtablecloth/TableCloth/assets/165000481/14341ab5-4e0b-4de6-9f5b-23f5cb3350cd

안녕하세요? 식탁보 1.12.3.0, #4a3928ae 버전을 사용하고 있는 유저입니다. 식탁보가 1.12버전으로 넘어오기 전에는 해당 오류가 발생하지 않았는데, 1.12버전부터 영상처럼 체크박스를 해제하고 안내에 따라 식탁보를 재시작해도 기존에 활성화 되어있던 체크박스가 비활성화 되지 않습니다. 

오류 자동 수집 비활성화 또는 새로운 인터페이스 사용 비활성화 모두 비활성화 할 수 없으며 반대로 프린터 함께 사용하기도 활성화 유지가 되지 않습니다. 

Windows 11 PRO / R7 5800x3D / 1.12.3.0, #4a3928ae 를 사용중이며 i7-1280h 프로세서를 사용하는 노트북에서도 동일한 증상이 발생합니다. 

1.9버전 이하의 식탁보를 설치한 후 설정하면 문제없이 잘 됩니다만 1.12버전 부터 설정이 적용되지 않습니다. 확인 부탁드립니다.

**Comment by rkttu** [comment]
1.3.0 버전 출시를 위한 작업 중에 이 문제를 수정한 것으로 확인하였습니다. 추후 문제가 다시 발견될 경우 이슈 re-open 부탁드리겠습니다.
