### ISSUE TITLE
공동 인증서 파일을 포렌식 저항성이 높은 방법으로 삭제할 수 있는 옵션 제공

### ISSUE THREAD

**Issue by rkttu** [yourtablecloth/TableCloth#209]
공동 인증서 파일처럼 누출될 경우 큰 위험을 수반하는 민감 데이터 파일을 좀 더 안정적으로 처리하기 위한 방안으로, 다음의 추가 옵션을 검토하고자 한다.

- 식탁보 시작 시 Windows 파티션이 BitLocker로 보호되고 있는 상태인지 검사하는 기능을 추가한다. BitLocker로 보호되고 있지 않을 경우, 장비 도난 등의 상황에서 보안이 취약할 수 있음을 경고한다.
- 샌드박스 실행 후, '공동인증서 사본 소각하기' 아이콘을 바탕 화면에 별도 애플리케이션으로 제공한다. 이 프로그램을 실행하면, `%localappdata%\..\LocalLow\NPKI` 폴더 이하 모든 파일을 보안 알고리즘 기반의 RNG로 만든 난수로 덮어쓰며, 덮어쓰기 횟수는 기본 3회 ~ 최대 9회까지 랜덤으로 수행한다.

피드백에 따른 추가 사항

- 공동인증서 사본 소각 기능은 샌드박스 세션이 어느 디스크 위에서 실행되는지 파악한 후, 드라이브 미디움 타입이 SSD가 아닌 경우에만 기능을 제공하도록 보완. SSD 타입의 경우 불필요한 작업이기도 하고, 디스크 수명을 깎을 수 있는 부분이 있어 좋지 않음.

**Comment by piquark6046** [comment]
Windows 시스템 파티션이 VeraCrypt 등 서드파트 암호화 유틸리티에 의해서 보호되어도 주의 메시지가 표시되나요?

**Comment by rkttu** [comment]
@piquark6046 VeraCrypt 등의 서드파티 암호화 유틸리티의 사용 여부를 고려하진 않습니다. 순수하게 BitLocker 사용 유무만 확인하여 경고를 표시하도록 만들었습니다.
