### ISSUE TITLE
[버그] 식탁보 프로젝트 시작 직후 서비스를 찾을 수 없다는 오류 메시지가 나타남

### ISSUE THREAD

**Issue by devhyuns** [yourtablecloth/TableCloth#210]
**버그에 대한 설명**
No service for type 'Microsoft.Extensions.Logging.ILogger' has been registered

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. 식탁보 설치 후 실행 하면 오류 발생

**기대하는 동작**

**동영상 또는 스크린샷**
![image](https://github.com/yourtablecloth/TableCloth/assets/167114047/3f8c9490-7a5b-41ed-823d-d8af1c2019d8)

**시스템 사양**
 - OS: Windows 10 Pro 22H2
 - CPU 아키텍처: Intel(R) Xeon(R) CPU E3-1230 V2
 - 브라우저: 크롬
 - 소프트웨어 릴리스 버전:  1.13.0.0

**참고 사항**

**Comment by rkttu** [comment]
@devhyuns 일단 오류 메시지에서 가리키는 내용은 잘못 코드가 작성된 부분이라 v1.13.1을 출시하여 수정했습니다. 그러나 실제 오류 원인이 무엇인지는 조사가 필요합니다.

혹시 괜찮으시다면, 다음 디버그 빌드를 설치하여 어떤 오류 메시지가 나타나는지 확인해주시면 감사하겠습니다.

https://github.com/yourtablecloth/TableCloth/actions/runs/8698669627/artifacts/1416532676

**Comment by devhyuns** [comment]
![image](https://github.com/yourtablecloth/TableCloth/assets/167114047/776a6973-27e6-43de-bdf7-b9f3b49370ad)

이렇게 나오고 식탁보 스플래시 화면에서 계속 로딩중만 나오고 진행이 안됩니다.

**Comment by rkttu** [comment]
고맙습니다. 프로그램에서 오류가 발생한 부분을 추적하려면 덤프 파일이 필요합니다. 가능하실 때, 아래 그림과 같이 작업 관리자의 덤프 생성 기능을 이용해 DMP 파일을 캡처해서 저에게 전달해주실 수 있을까요? 덤프 파일을 만들면 크기가 조금 크게 만들어질거라 Google Drive나 OneDrive 등의 수단으로 공유해주시면 좋을 것 같습니다.!

![image](https://github.com/yourtablecloth/TableCloth/assets/1297346/e71966c9-96d3-45f0-b99f-10c32cbfaf51)

**Comment by devhyuns** [comment]
좀 늦었습니다.
덤프파일 보내드립니다.

https://drive.google.com/file/d/1kiD1UHyLowWn-3oD74Mx9lcEY6DYxhYQ/view?usp=sharing


2024년 4월 22일 (월) 오전 8:47, Jung Hyun Nam ***@***.***>님이 작성:

**Comment by rkttu** [comment]
덤프 파일 분석 결과는 다음과 같습니다.

- 1.13.0 버전이 아닌 1.13.1 버전에서 수집된 덤프임을 확인하였습니다.
- 오류가 발생하는 부분은 프로그램 로딩 초기에 시각 테마를 확인하는 과정에서, `HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize` 키 아래에 `AppsUseLightTheme` 항목이 없는 경우에 발생하는 문제였습니다.

위의 문제를 수정하여 같은 상황이 나타나더라도 오류를 발생시키지 않도록 코드를 보강했습니다.

1.13.2 버전에 포함하여 출시할 예정입니다. 덤프 파일으 주신 덕분에 문제를 파악하고 수정할 수 있었습니다.
