### ISSUE TITLE
[제안] 샌드박스 저장

### ISSUE THREAD

**Issue by nooskuyh** [yourtablecloth/TableCloth#222]
**제안해주시는 기능이 소프트웨어로 인해 발생한 문제 때문인가요? 그렇다면 자세히 알려주세요.**
문제점에 대해서 간단하고 명료하게 알려주세요. 

샌드박스 종료 이후, 초기화가 반드시 필요한 지 궁금합니다.
재설치 없이 그 환경을 이용할 수는 없을까요?
보안상 혹은 샌드박스 정책 상 불가한가요? 중복된 이슈가 있다면 죄송합니다.

**어떻게 개선한다면 좋을까요?**
개선 방안에 대해서 간단하고 명료하게 알려주세요.

**다른 대안이 있을까요?**
만약 이 문제에 대한 다른 대안이 있다면 간단하고 명료하게 알려주세요.

**추가 맥락**
기능 제안에 관련된 다른 여러가지 부가 적인 정보도 있다면 기재해주세요.

**Comment by rkttu** [comment]
안녕하세요.

윈도우 샌드박스 자체의 기본 동작과 설계의도가 항상 내부 환경을 재설정하도록 만들어져있습니다.

내부 환경 유지가 필요하신경우, Hyper-V나 Vmware, 혹은 별도 스페어 PC에 인터넷 뱅킹 환경을 구축하시는 것이 해결책이 되겠습니다.
