### ISSUE TITLE
[제안] QT 기반 GUI로 변경 및 다크모드 지원

### ISSUE THREAD

**Issue by TK50P** [yourtablecloth/TableCloth#225]
**제안해주시는 기능이 소프트웨어로 인해 발생한 문제 때문인가요? 그렇다면 자세히 알려주세요.**
예, https://github.com/yourtablecloth/TableCloth/issues/220 와 https://github.com/yourtablecloth/TableCloth/issues/216 같이 .NET를 기반으로 한 프로그램들이 종종 오류를 내면서 실행이 안되는 모습을 보았습니다.
이 오류가 꼭 .NET 문제인지는 잘 모르겠습니다.

**어떻게 개선한다면 좋을까요?**
다음 릴리즈에서 .NET 기반을 QT로 변경했으면 좋겠습니다.
QT로 만든 GUI는 어떨지는 모르겠습니다만, QT로 변경하면 .NET보다 호환성이 높을 것으로 예상이 될 거 같습니다.
QT 기반으로 바꾸면서, 다크 모드도 지원했으면 좋겠습니다.
QT 버전같은 경우 Windows Sandbox가 애초에 Windows 7과 Windows 8/8.1을 지원하지 않으니 QT 버전은 6으로 해도 무관할 거 같습니다.

**다른 대안이 있을까요?**
.NET에 다크모드를 추가해도 좋을 거 같습니다만, QT가 더 나을 거 같습니다.
굳이 QT 말고도 구현이 어렵다면, GTK+나 다른 프레임워크를 사용해도 괜찮을 거 같습니다.

**추가 맥락**
QT나 GTK 버전은 무엇을 사용했는지 정보에 넣으면 좋을 거 같습니다.

**Comment by rkttu** [comment]
안녕하세요.

언급하신 이슈들은 WPF나 Windows Forms 런타임 이슈가 아니며, qt나 gtk로 이전해야할 동인과도 관련은 없습니다.

또한, 언급하신 이슈를 포함하여 문제를 개선하고, 아키텍처적으로 큰 변화를 만들 예정이어서 해당 이슈들은 지금 직접 다루고 있지 않습니다.

다만, 식탁보의 macOS 버전이나 리눅스 버전을 로드맵에서는 그리고 있으며, 이 때 사용할 GUI 툴킷으로는 말씀하신 qt나 gtk가 적절한 수단이라고 보고 있습니다.

**Comment by rkttu** [comment]
그리고 현재도 다크모드는 구현되어있습니다. 다크모드가 작동하지 않는 경우가 있는지 체크해보겠습니다만, 혹시 동작하지 않는 상황을 재현해주실 수 있을 경우, 이슈를 다시 열고 상세한 내용을 말씀 부탁드립니다.
