### ISSUE TITLE
[버그] Enabling WinSxS 안끝남 - Windows 11 IOT Enterprise LTSC

### ISSUE THREAD

**Issue by SJang1** [yourtablecloth/TableCloth#227]
**버그에 대한 설명**
`Enabling WinSxS` 작업이 안 끝납니다. 따라서, 이후 순차실행인 식탁보 Spork 특성상 프로그램 설치가 진행이 안됩니다.

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. Windows 11에서 Windows Sandbox 활성화
2. 식탁보 설치 및 실행
3. (국민은행으로 테스트) 샌드박스 실행

**기대하는 동작**
정상적으로 Spork 실행으로서 프로그램들 설치에 성공.

**동영상 또는 스크린샷**
![Screenshot from 2024-10-20 06-36-51](https://github.com/user-attachments/assets/0b3dc181-6edb-4bd7-a51b-a0b0c6d0201c)

**시스템 사양**
 - OS: Windows 11 IOT Enterprise LTSC 24H2 26100.2033
 - CPU 아키텍처: x64
 - 브라우저: Chrome (PC), Edge (Sandbox)
 - 소프트웨어 릴리스 버전: 1.13.2.0

**참고 사항**
Newly Fresh Installed Windows 11

**Comment by SJang1** [comment]
**Update**
약 5~10 분간의 대기 후 성공합니다. 너무 오래 걸리는 상황에 대한 확인 필요해 보입니다.

**Comment by hyunki** [comment]
식탁보 1.13.2 사용중인데 진짜 한 10분기다려야 진행 됩니다.
Ryzen5 5600
GTX 3070
Ram 32gb 
Windows 11 Pro 입니다.

**Comment by rkttu** [comment]
v1.14.0 출시와 함께 WinSxS 강제 패치 기능을 제거했습니다. 인터넷등기소 관련 문제는 프로그램 공통 기능이 아닌 개별 사이트 대응으로 다시 변경하여 진행하겠습니다.
