### ISSUE TITLE
[버그] 1.13.2 실행하기 버튼 무응답

### ISSUE THREAD

**Issue by LeeJuhyeong424** [yourtablecloth/TableCloth#233]
**버그에 대한 설명**
알기 쉽고 간결하게 발생하는 버그에 대한 내용을 알려주시면 감사하겠습니다.

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. ... 1.13.2 설치 이후 어떤 건이든 실행하기 버튼을 누르면 아무 반응을 일으키지 않습니다.
2. ...

**기대하는 동작**
버그가 발생하지 않았다면, 원래 어떻게 동작해야 하는지 간단하고 명확하게 알려주세요.
정상적으로 샌드박스가 실행되어 작업을 진행해야합니다.

**동영상 또는 스크린샷**

**시스템 사양**
 - OS: Microsoft Windows 11 Pro
 - CPU 아키텍처: 64비트
 - 브라우저:
 - 소프트웨어 릴리스 버전: 1.13.2

**참고 사항**
문제에 관련된 다른 언급할 사항이 있으면 기재해주시면 감사하겠습니다.

1.12 버전 실행시 정상적으로 실행되나 13으로 실행시에는 실행이 되지 않습니다. (12역시 화면깜빡임)

**Comment by rkttu** [comment]
알려주신 정보 만으로는 재현이 어렵습니다. 같은 이슈를 겪고 계시는 분들 가운데에서, 혹은 @LeeJuhyeong424 님께서 혹시 어떻게 실패하는지 구체적인 로그나 스택 트레이스를 보내주실 수 있을지 문의드립니다.

**Comment by rkttu** [comment]
1.13.2 태그를 기준으로 Visual Studio에서 코드를 빌드한 후 디버깅 과정을 보내주실 수 있다면 제일 좋을 것 같습니다.

하지만 이렇게 도움지시기 어려울 수 있으므로, 다음 릴리스 (1.14.x)에서 구체적인 로그를 남기는 방법을 추가하여 해당 빌드를 기준으로 로그를 수집할 수 있는 기능을 넣어 로그를 제출하실 수 있도록 준비해보겠습니다.

**Comment by LeeJuhyeong424** [comment]
1.14 버전으로 업데이트 이후 정상 작동합니다. :) 이슈를 종료해도 좋을거 같습니다.

**Comment by LeeJuhyeong424** [comment]
![image](https://github.com/user-attachments/assets/612e8f3f-4f5a-4700-a9b1-19cb3b4a8e44)
[debug_output.txt](https://github.com/user-attachments/files/18134562/debug_output.txt)
로그와 사진 함께 첨부드립니다 ;)

**Comment by rkttu** [comment]
고맙습니다! 이 문제도 새롭게 추가하려던 기능과 관련된 문제로 파악됩니다. 1.14.0 버전부터 보여주신 코드와 관련된 내용을 제거하여 프로그램을 단순화시켜 릴리즈했습니다. 혹시 1.14.0 버전에서도 문제가 반복되는지 확인해주시면 감사하겠습니다. 🙇

**Comment by LeeJuhyeong424** [comment]
1.14.0버전에서는 잘 작동합니다. 
오류 로그 수집하는 부분도 추가해주셨네요 감사합니다. :) 해당이슈는 1.14.0 버전에서 정상작동하여 종료하셔도 될거같습니다. >_<
