### ISSUE TITLE
프리셋 선택과 관계없이 사전 프로그램이 설치되지 않는 오류

### ISSUE THREAD

**Issue by gdaegeun539** [yourtablecloth/TableCloth#30]
빌드: 13a790e

오류 환경: Windows 10 21H1 x64
![image](https://user-images.githubusercontent.com/41503781/130590699-3ab6f6fe-d5bf-43b4-a7f1-06053d5df25c.png)

오류 내용: 사이트 프리셋 선택과 상관없이 사전 프로그램 설치가 진행되지 않음
(공동 인증서, 모두의 프린터 등은 정상 작동, 스크립트 자체는 샌드박스 부팅 후 실행됨)
![NewErr2](https://user-images.githubusercontent.com/41503781/130591382-7ebeaa9e-df64-449b-9281-cf6f9297504e.png)

**Comment by rkttu** [comment]
@gdaegeun539 안녕하세요. 0.5.1 버전을 업데이트하면서 MSIX 방식 대신 MSI 방식으로 패키징을 변경했습니다. 이전 방식은 실행 시 보안 제약이 강하게 걸려있어 제보해주신 문제가 나타나는것으로 보여 변경했습니다.

**Comment by gdaegeun539** [comment]
![Solved1](https://user-images.githubusercontent.com/41503781/131245862-cc651c0d-d839-4bfc-bb95-50b3dee2ec1c.png)

0.5.1 설치 후 실행하니 해당 버그까지 해결되네요. 감사합니다.
