### ISSUE TITLE
Windows 샌드박스 인식 불가

### ISSUE THREAD

**Issue by dokdo2005** [yourtablecloth/TableCloth#33]
Windows 샌드박스 기능을 켰음에도 불구하고 프로그램에서 샌드박스가 켜져 있지 않다는 오류가 뜹니다.

아래는 대략적인 제 PC 정보입니다.

![image](https://user-images.githubusercontent.com/6958819/130896795-f01315e1-458a-4b85-9e4c-38d5f44f7d4c.png)

**Comment by rkttu** [comment]
@dokdo2005 안녕하세요. 0.5.1 버전을 업데이트하면서 MSIX 방식 대신 MSI 방식으로 패키징을 변경했습니다. 이전 방식은 실행 시 보안 제약이 강하게 걸려있어 제보해주신 문제가 나타나는것으로 보여 변경했습니다.

**Comment by dokdo2005** [comment]
실행 잘 되네요. 따라서 이 이슈는 이제 닫도록 하겠습니다.
