### ISSUE TITLE
[제안] 설명서에 필수적인 내용이 추가적으로 들어가야 할듯 싶습니다.

### ISSUE THREAD

**Issue by parkpc** [yourtablecloth/TableCloth#44]
1. Windows Sandbox 가 Windows 10 및 Windows 11 Pro / Enterprise / Education 에서 작동하는 기능이기에 적격한 라이센스를 가지고 있어야 한다고 명시를 해야할 듯 합니다.
2. 식탁보를 사용 중 발생하는 개인,기업,기관의 금전손실,세금신고 누락 등을 비롯한 어떠한 장애나 손해에 대해서는 사용자 본인에게 책임이 있다는 부분을 명시하시고, 중요한 작업의 경우 실 PC환경에서 사용하는 것을 권장하셔야 할 것 같습니다. 필요하다면 식탁보사용시 이에 대한 동의과정을 받고 주기적으로 다시 확인시켜주는 과정이 필요할것 같습니다.

**Comment by rkttu** [comment]
프로그램 시작 시 일정 주기마다 디스클레이머를 표시하는 기능으로 추가하겠습니다. 제안 감사드립니다.

**Comment by rkttu** [comment]
식탁보 홈페이지에 우선 관련 내용을 추가했습니다.

https://yourtablecloth.github.io/
