### ISSUE TITLE
[버그] 특정 환경 (10 21H1)에서 WPF 앱이 빈 화면으로만 표시됨

### ISSUE THREAD

**Issue by johnpark-bin** [yourtablecloth/TableCloth#46]
**버그에 대한 설명**
알기 쉽고 간결하게 발생하는 버그에 대한 내용을 알려주시면 감사하겠습니다.

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. 특별한건 없고 실행시 매번 재현됩니다.

**기대하는 동작**
버그가 발생하지 않았다면, 원래 어떻게 동작해야 하는지 간단하고 명확하게 알려주세요.

**동영상 또는 스크린샷**
버그가 발생하기까지의 과정을 설명하는 동영상이나 스크린샷을 가능한 경우 첨부해주세요.

![Untitled](https://user-images.githubusercontent.com/313274/135723932-a47dc742-fb84-4a10-bf0b-fa12bb3c8c2f.png)

**시스템 사양**
 - OS: Windows 10 Pro 21H1
 - CPU 아키텍처: AMD Ryzen 7 1800X Eight-Core Processor
 - 브라우저: Firefox
 - 소프트웨어 릴리스 버전: 0.5.1 

**참고 사항**
문제에 관련된 다른 언급할 사항이 있으면 기재해주시면 감사하겠습니다.

https://github.com/yourtablecloth/TableCloth/discussions/37#discussioncomment-1262616

이 분이 언급하신 내용과 동일한 증상으로 보입니다.

**Comment by rkttu** [comment]
죄송하지만 이슈 해결이 어려울 것 같습니다.

식탁보에서는 WPF를 사용하면서 특별한 패치나 핵을 적용한 것이 아니어서, 이 부분은 소스 코드 수준에서 디버깅을 진행하면서 어디서 UI 렌더링이 실패하는지를 추적해 보는 것이 최선인 상항입니다.

코드 레벨에서 디버깅에 도움을 주실 수 있다면 감사하겠습니다.

**Comment by rkttu** [comment]
이번에 새로 업데이트한 0.5.2 버전에서는 닷넷 런타임을 5.x에서 6.x로 업데이트하여 다시 빌드했습니다. WPF의 내부 문제로 발생한 이슈라면 이 문제가 혹시 해결되었을 수 있는데, 새 빌드를 받아 실행했을 때는 어떤지 새로 확인이 필요한 상황이라, 일단 이 이슈는 닫겠습니다. 필요한 경우 다시 오픈 가능합니다.

0.5.2 버전 다운로드: https://github.com/yourtablecloth/TableCloth/releases/tag/v0.5.2
