### ISSUE TITLE
[제안] ApplicationLog를 저장하는 폴더 경로를 변경하는 기능

### ISSUE THREAD

**Issue by KimPinot** [yourtablecloth/TableCloth#58]
**제안해주시는 기능이 소프트웨어로 인해 발생한 문제 때문인가요? 그렇다면 자세히 알려주세요.**
프로그램을 실행시킬때마다 경고를 포함한 로그가 생성될 경우 바탕화면에 폴더가 만들어집니다.

**어떻게 개선한다면 좋을까요?**
바탕화면 대신 문서 폴더에 로그를 저장해야 합니다.
또는, 식탁보 앱 설치시 로그의 경로를 설정하는 기능의 추가가 있으면 좋을 것 같습니다.

**다른 대안이 있을까요?**
지금 단계에서 다른 대안은 생각이 나지 않습니다. 다른 좋은 기능이 있다면 같이 생각해 보는 것도 좋을 것 같네요 :)

**추가 맥락**
프로젝트를 실행시킬 때마다 다음과 같은 경고가 출력됩니다.
별도의 이슈로 만들까 생각하다가, 우선 해당 이슈에 같이 붙여넣겠습니다.

```json
{
  "Timestamp": "2022-01-13T16:47:49.2429581+09:00",
  "Level": "Warning",
  "MessageTemplate": "Cannot load X509 cert pair - D:\\NPKI\\KICA\\USER\\cn=OOO79,ou=RA센터,ou=OO은행,ou=등록기관,ou=licensedCA,o=KICA,c=KR",
  "Exception": "System.InvalidOperationException: Sequence contains more than one element\r\n   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()\r\n   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)\r\n   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)\r\n   at TableCloth.Implementations.X509CertPairScanner.ScanX509Pairs(IEnumerable`1 rootPathList) in D:\\a\\TableCloth\\TableCloth\\src\\TableCloth\\Implementations\\X509CertPairScanner.cs:line 76",
  "Properties": {
    "SourceContext": "TableCloth.Implementations.X509CertPairScanner"
  }
}
```

**Comment by rkttu** [comment]
공인인증서 폴더가 프로그램이나 샌드박스 종료 전후로 의도치않게 남는 문제를 예방할 목적으로 눈에 잘 띄도록 설계를 변경한 결과입니다. 폴더의 위치를 사용자가 인지하고 바로 삭제할 수 있도록 돕기 위함이었습니다.

하지만 바탕화면 대신 다른 위치에 저장할 수 있도록 기능을 추가하는것은 신 기능으로 추가해보겠습니다. 👍

**Comment by rkttu** [comment]
아울러 해당 로그도 같이 살펴보겠습니다. 👍
