### ISSUE TITLE
[버그] 프로그램이 시작되지 않습니다.

### ISSUE THREAD

**Issue by miriamme** [yourtablecloth/TableCloth#59]
**버그에 대한 설명**
설치 후 프로그램을 실행하면 조금 있다가 그냥 꺼집니다.

**재현 방법**
1. 윈도우 샌드박스 기능 추가
2. 재부팅
3. 식탁보 설치
4. 프로그램 실행

**동영상 또는 스크린샷**
<img width="591" alt="화면 캡처 2022-01-22 112715" src="https://user-images.githubusercontent.com/24400295/150621376-45eddaf6-9ff5-4bc1-bb1d-b17a829510db.png">

**시스템 사양**
<img width="516" alt="화면 캡처 2022-01-22 112823" src="https://user-images.githubusercontent.com/24400295/150625452-08e14bcc-88b0-47ab-bf40-f3849418c04a.png">

**참고 사항**
ApplicationLog.josnl 에 남겨진 로그정보 남깁니다.
```
{"Timestamp":"2022-01-22T11:23:29.5401723+09:00","Level":"Warning","MessageTemplate":"Cannot load X509 cert pair - C:\\Users\\chokije\\AppData\\LocalLow\\NPKI\\yessign","Exception":"System.InvalidOperationException: Sequence contains more than one element\r\n   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()\r\n   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)\r\n   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)\r\n   at TableCloth.Implementations.X509CertPairScanner.ScanX509Pairs(IEnumerable`1 rootPathList) in D:\\a\\TableCloth\\TableCloth\\src\\TableCloth\\Implementations\\X509CertPairScanner.cs:line 76","Properties":{"SourceContext":"TableCloth.Implementations.X509CertPairScanner"}}
```

**Comment by rkttu** [comment]
제보 감사드립니다. 첨부한 아래 그림처럼 der 파일이나 key 파일이 디렉터리에 유일하게 한 쌍으로 들어있는 경우가 아닐 때 발생하는 오류로 보이는데, 혹시 위 디렉터리에 인증서 파일이 어떻게 들어있는지 알 수 있을까요?

![image](https://user-images.githubusercontent.com/1297346/150641354-3d5fb198-3d6f-48b0-bd1a-ff6131b3f1a8.png)

**Comment by miriamme** [comment]
인증서 파일은 아래 캡처 이미지처럼 들어 있습니다.

<img width="448" alt="화면 캡처 2022-01-23 032240" src="https://user-images.githubusercontent.com/24400295/150650880-a323af23-173d-4797-804b-79a78780c2a2.png">

**Comment by rkttu** [comment]
d356155bd9f3b56d93e0f4fdb4462d2146981d1b 커밋 기준으로 der 파일과 key 파일을 찾는 방식 대신 signCert.der, signPri.key 파일을 찾도록 인증서 매칭 로직을 수정했는데, 현재 dev 브랜치 기준으로도 문제가 계속 발생하는지 확인해주실 수 있을까요?

**Comment by miriamme** [comment]
dev 브랜치로 실행해본 결과 여전히 오류가 발생합니다.
<img width="1193" alt="01" src="https://user-images.githubusercontent.com/24400295/150688278-ef21a6bd-5f13-4a29-aa92-c4ff73cfc327.png">

SingleOrDefault() 대신에 FirstOrDefault() 사용시 정상 작동 했습니다.
```csharp
var foundCandidate = ViewModel.CertPairScanner.ScanX509Pairs(ViewModel.CertPairScanner.GetCandidateDirectories()).FirstOrDefault();

if (foundCandidate != null)
{
    ViewModel.SelectedCertFile = foundCandidate;
    ViewModel.MapNpkiCert = true;
}
```
하나의 인증서는 SingleOrDefault()가 맞으나 여러개의 경우에는 throw 처리를 해버리니, 여러개를 가지고 있을 경우에는 FirstOrDefault()가 더 좋아 보이네요. 없으면 null 이 되므로 다음 코드에도 맞을 것 같구요.
저도 예전에 자주 하던 실수여서 왠만하면 FirstOrDefault()를 사용합니다.

<img width="591" alt="02" src="https://user-images.githubusercontent.com/24400295/150688651-53a0b9c3-2b84-4643-8d86-b130a5634a4b.png">

**Comment by rkttu** [comment]
코드 리뷰와 제안 감사드립니다! `SingleOrDefault`를 잘못 이해하고 사용한 부분이 계속 문제가 되는지 파악하지 못했습니다. dev 브랜치에 관련된 수정 사항을 반영했는데, 리뷰 한 번 더 부탁드리겠습니다. (해당 커밋 ID는 7bd9deb819edaeea5efb67cc9d8f64a098888f55 입니다.)

**Comment by miriamme** [comment]
이상없이 잘 작동합니다.
