### ISSUE TITLE
[버그] 카탈로그 불러오기 오류

### ISSUE THREAD

**Issue by dokdo2005** [yourtablecloth/TableCloth#60]
**버그에 대한 설명**
알기 쉽고 간결하게 발생하는 버그에 대한 내용을 알려주시면 감사하겠습니다.

식탁보에서 접속할 사이트를 선택하고 실행하면 스크린샷의 오류가 뜹니다.

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. 식탁보에서 접속할 사이트를 선택하고 실행하면 스크린샷의 오류가 뜹니다.
2. ...

**기대하는 동작**
버그가 발생하지 않았다면, 원래 어떻게 동작해야 하는지 간단하고 명확하게 알려주세요.

**동영상 또는 스크린샷**
버그가 발생하기까지의 과정을 설명하는 동영상이나 스크린샷을 가능한 경우 첨부해주세요.
![image](https://user-images.githubusercontent.com/6958819/152096703-e3bd760b-6ac3-47c0-8257-a63dd7a2f505.png)

**시스템 사양**
 - OS: Windows 10 Pro
 - CPU 아키텍처: AMD Ryzen 3700X
 - 브라우저: Microsoft Edge
 - 소프트웨어 릴리스 버전: 0.5.2

**참고 사항**
문제에 관련된 다른 언급할 사항이 있으면 기재해주시면 감사하겠습니다.

**Comment by rkttu** [comment]
혹시 yourtablecloth.github.io 자체는 브라우저에서 접속하실 때 접속이 잘 되시나요? SSL 관련 이슈인지 살펴보기 전에 확인차 질문드립니다.

일단 위 사이트 자체는 GitHub 인프라여서 제가 볼 수 있는 부분은 제한적입니다.

**Comment by dokdo2005** [comment]
> 혹시 yourtablecloth.github.io 자체는 브라우저에서 접속하실 때 접속이 잘 되시나요? SSL 관련 이슈인지 살펴보기 전에 확인차 질문드립니다.
> 
> 일단 위 사이트 자체는 GitHub 인프라여서 제가 볼 수 있는 부분은 제한적입니다.

해당 사이트 자체는 접속이 잘 됩니다.

**Comment by rkttu** [comment]
정확히 재현할 수 없지만 올려주신 스크린 샷을 봤을 때는 샌드박스 내에서 카탈로그 다운로드가 실패하는 상황으로 보이며, 프로그램의 로직을 수정하여 샌드박스 밖에서 카탈로그 파일을 받도록 변경해보겠습니다.

**Comment by rkttu** [comment]
#107 에서 제안된 대로 retry logic을 추가할 예정입니다.
