### ISSUE TITLE
필요한 파일을 미리 다운로드하는 동작 구현

### ISSUE THREAD

**Issue by rkttu** [yourtablecloth/TableCloth#63]
카탈로그 파일 뿐 아니라 연관된 종속성 파일들을 미리 다운로드받아 샌드박스 안으로 전달하도록 로직을 수정할 필요가 있다.

샌드박스 안에서 네트워크가 차단되는 케이스가 있어 보완이 필요해 보인다. (#60)

**Comment by Sunday5214** [comment]
@rkttu @level120 해당이슈 제가 작업해봐도 될까요?

**Comment by rkttu** [comment]
@Sunday5214 좋습니다.

**Comment by rkttu** [comment]
추후 필요시 다시 작업하겠습니다.
