### ISSUE TITLE
[제안] 샌드박스 언어팩

### ISSUE THREAD

**Issue by Kuass** [yourtablecloth/TableCloth#73]
**제안해주시는 기능이 소프트웨어로 인해 발생한 문제 때문인가요? 그렇다면 자세히 알려주세요.**
제 Windows 의 메인 언어가 English 로 되어 있고, 두번째로 한국어 언어팩이 깔려 있는데요, 식탁보를 통해 윈도우 샌드박스가 실행되면 기존에 English 로만 설정이 되어있고 한국어를 입력하기 위해서는 매번 설정에 가서 한국어를 추가해야 하는 번거로움이 있습니다.

PC 에 이미 한국어 언어팩이 깔려있어서 그런지 추가하니까 설치과정 없이 바로 한국어 입력이 가능해지긴 하더군요!

![image](https://user-images.githubusercontent.com/5186106/156989099-9fd0be20-3719-4a30-8dd4-44a55796a256.png)
직접 한국어팩을 추가한 이미지 입니다 :)

**어떻게 개선한다면 좋을까요?**
기존 PC 의 언어팩 설정을 그대로 적용하거나 한국어 언어팩을 강제로 추가하는 방법이 있겠습니다.

감사합니다.

**Comment by rkttu** [comment]
윈도우 샌드박스의 기본 이미지는 호스트 OS를 따라가도록 되어있어서 그런 것 같습니다. 몇 가지 구현 상에 확인해봐야 할 내용들이 있어서 쉽지는 않을 것 같습니다.

1. 한국어 언어 팩이 설정되어있는지 프로그래밍방식으로 확인할 방법
2. Windows PowerShell Management Pack 레벨에서 한국어 언어 팩을 추가할 수 있는 Cmdlet이 존재하는지 확인하고 테스트하기
3. 만약 샌드박스 내에서 처리할 방법이 없다면, 호스트 OS에서 이를 확인하고 사용자에게 통지하는 방법

위의 내용들을 담은 새 이슈를 만들어 프로젝트 To Do 리스트에서 관리해보겠습니다. 제보 감사드려요.!

**Comment by rkttu** [comment]
PowerShell cmdlet을 이용해서 설치/제거를 할 수 있음을 확인했습니다만 (LanguagePackManagement 모듈), ms-settings 애플리케이션을 이용해서 제어하는 것과는 달리 PowerShell로는 샌드박스 내에서 언어를 추가/제거하는 것이 실패합니다.

대신 아래의 대안을 사용할 수 있고, 이는 샌드박스 베이스 이미지를 수정하지 않는 한도 내에서의 최선책이라 사용자 가이드 상에서 이를 안내하는 형태로 보완하고자 합니다.

- 샌드박스 재부팅 기능이 구현된 Windows 11이 필요합니다.
-  `ms-settings:regionlanguage-adddisplaylanguage` URI를 통해 디스플레이 언어 추가/제거 화면을 엽니다.
- 대한민국/한국어 설정을 추가합니다.
- 기본 시스템 로캘 설정을 한국어 우선으로 변경합니다.
- 샌드박스를 재부팅합니다. (Windows 11 미만의 OS에서는 재부팅이 없고, 종료만 가능합니다.)
- 한국어 설정이 적용된 것을 볼 수 있습니다.

이와 같이 한국어 설정을 수동으로 적용할 수 있는 것으로 보입니다. 그러나 이 설정을 프로그래밍 방식으로 적용하는 것은 2023년 7월 현재 적절한 방법을 찾지 못했습니다.

이 이슈는 일단 닫습니다. 그러나 추후 더 좋은 방법이나 확장의 여지가 있다면 다시 살펴보고자 합니다.
