### ISSUE TITLE
[버그] Windows 샌드박스를 초기화하지 못했습니다.

### ISSUE THREAD

**Issue by siyoung5100** [yourtablecloth/TableCloth#76]
**버그에 대한 설명**
식탁보에서 샌드박스 실행하면 스크린샷과 같은 오류가 발생합니다.
windows 샌드박스 자체는 정상적으로 작동하는 것을 확인했습니다.

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. 식탁보를 열고 샌드박스를 실행시키면 증상이 발생합니다.

**기대하는 동작**
버그가 발생하지 않았다면, 원래 어떻게 동작해야 하는지 간단하고 명확하게 알려주세요.

**동영상 또는 스크린샷**
![image](https://user-images.githubusercontent.com/53399722/162564861-07040218-9cca-46ea-809f-b39ead2f40cd.png)
**시스템 사양**
 - OS: Windows 11 Education
 - CPU 아키텍처: AMD64
 - 브라우저: Brave
 - 소프트웨어 릴리스 버전: 0.5.4.0

**참고 사항**
문제에 관련된 다른 언급할 사항이 있으면 기재해주시면 감사하겠습니다.

**Comment by rkttu** [comment]
발생한 HREUSLT 오류 코드는 ERROR_MRM_INVALID_FILE_TYPE 이고, 식탁보가 동적으로 생성하는 WSB 파일을 제대로 인식하지 못해서 발생하는 오류인 것 같습니다. 그런데 사용하시는 PC에서만 발생하는 원인이 무엇인지 파악하는데 한계가 있습니다.

가능하시면 식탁보 소스 코드를 빌드하여 디버깅하면서 원인을 찾아주실 수 있다면 좋겠습니다. 일단 저도 관련된 내용이 있는지 최대한 리서치해보겠습니다.

**Comment by rkttu** [comment]
혹시 식탁보를 통하지 않고, 아래 레퍼런스 문서에서 설명하는대로 WSB 파일을 직접 텍스트 에디터로 만들어서 구동하려고 했을 때는 어떤지 확인해주시면 감사하겠습니다.

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file

**Comment by cloim** [comment]
동일한 증상의 문제를 겪었습니다. 
WindowsSandbox.exe 호출 방법을 변경해보니 정상 동작함을 확인하였습니다. 관련하여 PR 하였으니 확인바랍니다 ;)
