### ISSUE TITLE
[제안]컬쳐랜드 지원 추가

### ISSUE THREAD

**Issue by kdh8219** [yourtablecloth/TableCloth#78]
**어떻게 개선한다면 좋을까요?**
컬쳐랜드 웹사이트에 컴퓨터로 로그인 할 때 touchenkey를 설치해야 합니다.
https://www.cultureland.co.kr/etc/touchen_install.do
https://www.cultureland.co.kr/
식탁보에서 지원해주시면 편리하게 이용할 수 있을 것 같습니다!

**Comment by kdh8219** [comment]
혹시 
https://github.com/yourtablecloth/TableClothCatalog
여기 Catalog.xml 만 수정해서 pull request 하면 되는건가요?

**Comment by rkttu** [comment]
@kdh8219 네. 맞습니다!

**Comment by rkttu** [comment]
카탈로그에 추가는 했지만, 카테고리를 새로 추가할 필요가 있어 아직 활성화하지 못했습니다. 다음 버전 릴리스 때 활성화할 수 있도록 하겠습니다. 🙏

**Comment by kdh8219** [comment]
아 이러면 안되는거였군요..ㅋㅋ 죄송합니다 아직 제가 깃헙에 익숙치가 않아서..
@rkttu
