### ISSUE TITLE
바탕 화면 바로가기 생성 기능 추가

### ISSUE THREAD

**Issue by rkttu** [yourtablecloth/TableCloth#81]
바탕 화면 바로가기 생성 기능을 추가하여 편의성을 개선한다. 커맨드라인 기능을 응용하여 구현한다.

![image](https://user-images.githubusercontent.com/1297346/175821201-93184301-d7a2-4fe8-932b-2d2d9a4d8111.png)

**Comment by leedonggyu1848** [comment]
@rkttu 이 이슈 제가 해봐도 될까요?

**Comment by level120** [comment]
혹시 여기서 의도하신 것이 바탕화면 바로가기만 클릭해도 마지막 설정한 값으로 실행하는 그런 내용일까요?
예를들어 우리은행을 선택하고 인증서 파일 선택한다음 바로가기를 만들었다면 내부 동작은 대략 아래처럼 동작하는 것 입니다.
* name:  `tablecloth.lnk`
* path: `{PROGRAM_PATH}\tablecloth.exe --bank woori --certificate "C:\Some.pfx"`

**Comment by leedonggyu1848** [comment]
@rkttu "커맨드라인 기능을 응용하여 구현한다." 라는 것이 어떤 것을 의미하나요?
tablecloth 실행파일에 인수를 넣어 특정 사이트의 바로가기를 만든다는 뜻 인가요?

**Comment by rkttu** [comment]
@leedonggyu1848 네. 맞습니다.

**Comment by rkttu** [comment]
https://github.com/yourtablecloth/TableCloth/pull/94
이 이슈와 연결된 기능이 잘 구현된 것으로 보여서, 이슈를 닫도록 하겠습니다.
