### ISSUE TITLE
[제안] 즐겨찾기 버튼 추가

### ISSUE THREAD

**Issue by bakukun** [yourtablecloth/TableCloth#82]
**어떻게 개선한다면 좋을까요?**
사용자마다 이용하는 은행이 전부 제각각이고 이용하는 기업이 한정 되어있기 때문에 유용하다고 판단하여 즐겨찾기 기능을 추가하는 것을 건의합니다
.

**Comment by Sunday5214** [comment]
@rkttu @level120 해당 이슈 작업해봐도 될까요?

**Comment by 201611099** [comment]
이 이슈는 저희 팀에서 해결해도 될까요?
@rkttu

**Comment by level120** [comment]
팀 단위는 구분하기 어려우니 @rkttu 님 확인 받으시면 @201611099 님께서 담당해주세요.

**Comment by 201611099** [comment]
@level120 넵 감사합니다!

**Comment by rkttu** [comment]
@201611099 좋습니다!

**Comment by bakukun** [comment]
예상 UI 같이 첨부해드립니다!
![캡처4 복사 (1)](https://user-images.githubusercontent.com/50573818/181879060-ecbf07a2-f2ed-4564-a4eb-194c5c5f3758.jpg)

**Comment by bakukun** [comment]
저희 B팀에서 맡기로 했던 즐찾 이슈는 팀 내부 논의 결과,
더 이상 저희 팀에서 맡지 않는 방향으로 진행될 것 같습니다.
다른 팀원 분들이 이 이슈를 맡아주셔도 좋을 것 같습니다!

**Comment by boeunnam** [comment]
즐겨찾기 제안 진행이 중단된것 같아 안타깝네요 ㅠㅠ
일반사용자에게는 반드시 필요해요

**Comment by rkttu** [comment]
@boeunnam 프로젝트가 한동안 개발이 중단된 상태여서 아직 해결되지 못했지만, 개발 예정인 기능입니다. 피드백 주셔서 고맙습니다!

**Comment by atawLee** [comment]
이내용을 작업중 이신가요?아직 손대신게 아니라면 2024 닷넷데브 서울 이벤트 끝날때 맞춰서 이 이슈 작업을 시작하려고 합니다.

**Comment by rkttu** [comment]
@atawLee 얼마전에 코드 리팩토링을 대대적으로 진행해서 예전에 보셨던 코드와 매우 많이 달라져있을 겁니다. (특히 MVVM과 DI/IoC 도입으로 크게 달라졌습니다.) 이 점을 참고하셔서 기능을 PR로 올려주시면 감사하겠습니다. 👍

**Comment by atawLee** [comment]
![image](https://github.com/yourtablecloth/TableCloth/assets/34878017/c82c10f8-4aa9-4c97-80ec-163455ab7561)
UI는 이런식으로 기존 아이콘 우측상단에 favorite아이콘버튼을 추가할 계획입니다. 

Favorite에 지정되는 경우 PreferenceManager를 통해서 
json 파일에 
"Favorite" : [1,2]
(숫자는 service id )
으로 넣을 생각입니다. 혹시 다른 의견 있으시면 알려주세요

**Comment by rkttu** [comment]
아주 좋습니다. 기본적인 기능 검증 후 풀리퀘스트를 보내주시면 감사하겠습니다!

**Comment by rkttu** [comment]
@atawLee PR을 보내주실 수 있는 시점이 언제즈음인지 알 수 있을까요? 새 버전 개발에 착수할 예정이라 여쭙습니다.

**Comment by atawLee** [comment]
> @atawLee PR을 보내주실 수 있는 시점이 언제즈음인지 알 수 있을까요? 새 버전 개발에 착수할 예정이라 여쭙습니다.

이번 주말 중 PR올릴 예정입니다.

**Comment by rkttu** [comment]
#193 PR을 merge하였습니다. 다음 릴리스에서 이 이슈의 제안 사항을 반영한 기능을 포함하여 출시할 예정입니다. @atawLee 님 고맙습니다!
