### ISSUE TITLE
[제안]주의사항 관련 UI개선

### ISSUE THREAD

**Issue by Konay889** [yourtablecloth/TableCloth#83]
식탁보 프로젝트를 돌리다 보니, 주의사항 문구를 확인할 수가 있는데,

이 주의사항 문구의 폰트가 모두 빨간색이라서, 가독성과 식별성이 약간 떨어질거 같아서

이 폰트들 중에서 중요한 사항들만 텍스트를 변경하고, 나머지 폰트는 무난한 폰트로 바꾸는게 어떨까요?

**Comment by rkttu** [comment]
관련된 PR을 보내주시면 검토해보겠습니다.
