### ISSUE TITLE
[제안] 주의사항 기능 추가

### ISSUE THREAD

**Issue by juyonLee00** [yourtablecloth/TableCloth#85]
프로그램을 처음 실행할 때 주의사항 창이 뜨는데, 창을 일주일 동안 없앨 수 있는 기능의 버튼만 있습니다.

아래와 같이 ui를 변경하고 창 닫기 버튼을 추가하려고 합니다.
![image](https://user-images.githubusercontent.com/48848525/181515908-4f6251dc-32f9-4753-b954-e8b1fd682fe3.png)

**Comment by rkttu** [comment]
좋습니다. 관련된 PR을 보내주시면 검토해보겠습니다.
