### ISSUE TITLE
[버그] Github Action 빌드 실패

### ISSUE THREAD

**Issue by level120** [yourtablecloth/TableCloth#86]
라이선스 파일을 제대로 인식하지 못하는 것으로 보입니다.

https://github.com/yourtablecloth/TableCloth/runs/7574895577?check_suite_focus=true

**Comment by rkttu** [comment]
이 부분은 PR을 보내주시는 분께서 수정해서 통과가 되도록 고쳐주셔야 할 것 같습니다.

**Comment by ChJR** [comment]
제출자마다 다르게 동작하는 것처럼 보입니다.
예를 들어 머지된 Actions의 로그를 보면 Decode the pfx 단계에서 $pfx_cert_byte = [System.Convert]::FromBase64String(“***“) 와 같이 남아 있지만, 문제가 발생했던 Actions의 로그에는 동일 단계에서는 $pfx_cert_byte = [System.Convert]::FromBase64String(“”) 와 같이 뭔가가 입력되지 않은 것처럼 보입니다.

**Comment by rkttu** [comment]
확인 결과, RTF 파일 경로를 찾는 부분에서 GitHub Action의 환경과 맞지 않는 부분이 있어 수정했습니다.
https://github.com/yourtablecloth/TableCloth/pull/93 에서 확인 결과 문제가 해결되었습니다.
