### ISSUE TITLE
[버그] 특정 은행을 실행할 경우 강제로 샌드박스가 종료됩니다.

### ISSUE THREAD

**Issue by juyonLee00** [yourtablecloth/TableCloth#88]
**버그에 대한 설명**
window 10 edu에서 KDB산업은행을 실행할 경우 샌드박스에서 강제로 실행이 종료됩니다.

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. 식탁보 프로그램을 실행한 후, KDB산업은행만 클릭한 후 샌드박스 실행 버튼을 클릭합니다.
2. 정상적으로 프로그램이 샌드박스에 설치될 때까지 기다립니다.
3. 프로그램을 다 설치한 후, 샌드박스가 웹사이트를 실행시킬 때까지 기다립니다.

**기대하는 동작**
버그가 발생하지 않았다면, 원래 어떻게 동작해야 하는지 간단하고 명확하게 알려주세요.

**동영상 또는 스크린샷**

첫 번째 사진과 같이 안랩에 관련된 알림창이 뜬 후 두 번째 사진처럼 샌드박스와의 연결이 끊겨진 에러창이 뜹니다.
![image](https://user-images.githubusercontent.com/48848525/185732112-d671c79c-de22-433e-9e80-a9aa6ad9f9ea.png)

![image](https://user-images.githubusercontent.com/48848525/185732158-96ea171f-46dc-4acb-a34b-b9764ce06f17.png)

**시스템 사양**
 - OS: Microsort Windows 버전 21H1(OS 빌드 19043.1826)
 - CPU 아키텍처: 
 - 브라우저: 
 - 소프트웨어 릴리스 버전: 식탁보 0.5.4 버전
 -
![image](https://user-images.githubusercontent.com/48848525/185732235-70f235cb-c136-4f5a-b7eb-8194d1a163fb.png)
![image](https://user-images.githubusercontent.com/48848525/185732246-c5bfa6a2-e78f-444f-bf2e-109533db441f.png)

**참고 사항**
문제에 관련된 다른 언급할 사항이 있으면 기재해주시면 감사하겠습니다.

**Comment by leedonggyu1848** [comment]
저도 KDB산업은행, 카카오뱅크, 한국투자증권 등 많은 annlab safe transaction을 사용하는 많은 사이트가 되지 않습니다.
window 10 edu사용중입니다.

**Comment by rkttu** [comment]
이 문제는 알려진 문제이며, 해결이 불가합니다.

- AhnLab Safe Transaction은 RDP에서 실행되는 것을 확인하면 강제로 RDP 프로세스를 종료하는 동작이 의도적으로 구현되어있습니다.
- 샌드박스의 경우 RDP 프로세스가 닫히면 샌드박스 컨테이너 자체가 파기되는 것이 기본 동작이며, 재정의할 수 있는 방법이 없습니다.
- 이 문제를 완화하기 위하여 RDP 프로세스를 강제 종료할 수 없도록 보호할 수 있는 방법이 있는지 찾아봤지만, Detour 같은 라이브러리를 이용할 수 있는 상황이 아니어서 프로세스 종료를 막을 방법이 없습니다.

일단은 이런 문제가 발생하는 사이트가 있을 경우, 해당 사이트에 `CompatNote` 태그를 카탈로그에 추가하여 이런 상황이 발생할 수 있음을 고지하는 것이 최선입니다.

이 문제에 대한 개선책이 확인되는대로 보완할 예정이지만, 현재로서는 보완책 적용이 쉽지 않을 것 같습니다.

**Comment by rkttu** [comment]
나무위키 설명 (https://namu.wiki/w/Windows%20%EC%83%8C%EB%93%9C%EB%B0%95%EC%8A%A4#s-2)에 따르면, AST 설정에서 원격 접속 차단 설정을 화면에서 직접 끌 수 있는 경우, 해당 설정을 끄면 문제가 해결되는 것 같습니다.

![image](https://user-images.githubusercontent.com/1297346/185757841-ecba266a-2462-4d07-88e0-e208f3154f73.png)

혹시 이렇게 해서 해결이 되는지 살펴봐주시면 감사하겠습니다. @juyonLee00  @leedonggyu1848

**Comment by leedonggyu1848** [comment]
상기한 방법을 이용해보니 문제 없이 실행됩니다. @rkttu

**Comment by level120** [comment]
@rkttu 이 내용을 소개하는 가이드 문서가 없다면 하나 추가할까요? 꽤 좋은 내용인 것 같아서요.
그리고 CompatNote도 좋지만 이를 은행 선택할 때 알 수 있으면 좋을 것 같은데 UI 상 태그 같은 것을 넣을 수 있는지 한 번 검토해봐야겠네요.

**Comment by juyonLee00** [comment]
@rkttu 저도 위 방법대로 하니 정상적으로 실행됩니다. 그리고 해당 내용을 소개하는 가이드 문서 추가도 좋은 의견이라 생각합니다.

**Comment by Sunday5214** [comment]
관련해서 발견 당시(2022. 08. 22)기준 윈도우 11(21H2,  빌드번호확인필요, Pro InsiderProgram)이었던 제 컴퓨터에서는 정상 작동하는 것으로 확인을 했었는데, (AST설정에서 Block Remote Access가 켜져있었습니다.) 

현재(2022. 08. 24) 다른 윈도우 11(21H2,  22000.856, Enterprise) 컴퓨터에서는 똑같이 종료되는 것으로 확인했습니다.

**Comment by skyrise97** [comment]
RDP 차단을 하지 않는 타 은행 사이트에서 먼저 AST 세션을 켠 뒤 AST 차단을 하는 은행 사이트로 접속하면 AST가 이미 실행된 것으로 판단해 진행하면서 RDP 차단에 걸리지 않는 것으로 알고 있습니다. 이를 통한 우회 방법은 없을까요?

**Comment by rkttu** [comment]
(개발자 노트) https://github.com/yourtablecloth/TableClothCatalog/pull/16

**Comment by crucifyer** [comment]
좋은것 만들어주셔서 감사합니다.
설치시에 구별이 되니 ast가 자동설치되는 이 시점에서 꺼야하는 옵션 위치 스크린샷을 노출시키고, 브라우저에 사이트를 띄우는 것은 자동이 아닌 버튼으로 처리하면 어떨까요?
스샷용으로 정리해봤습니다.
감사합니다. ^^ @rkttu 
![image](https://github.com/yourtablecloth/TableCloth/assets/1300668/261369bc-ff50-4667-8db6-fb81b56b1a47)
![image](https://github.com/yourtablecloth/TableCloth/assets/1300668/8d18a87b-56b8-4c06-96d2-7f5c3d2e6bce)
![image](https://github.com/yourtablecloth/TableCloth/assets/1300668/8217b4cd-75e5-4d87-a2e0-4df8075f7157)

**Comment by crucifyer** [comment]
그리고, 닫기 전에 새로 발급받은 (갱신한) 인증서를 복사하기 편리하도록 `%USERPROFILE%\AppData\LocalLow\NPKI\yessign\USER\` 를 링크로 넣어놓으면 좋을 것 같네요.
