### ISSUE TITLE
[제안] 접속할 사이트 선택 UI 개선

### ISSUE THREAD

**Issue by juhyeon-cha** [yourtablecloth/TableCloth#89]
**제안해주시는 기능이 소프트웨어로 인해 발생한 문제 때문인가요? 그렇다면 자세히 알려주세요.**
중요한 이슈라기보단 사용자 편의를 위한 기능으로 다른 이슈사항보단 중요도가 낮을 것 같습니다.

**어떻게 개선한다면 좋을까요?**
현재 웹사이트에 분류가 전부 지정되어 있던데, 그리드 형태로 사이트를 선택해서 최종적으로는 더블클릭 시 샌드박스 실행이 되면 좋을 것 같습니다.

이런 제안에 대한 배경으로는
1. 처음 식탁보를 사용하는 사용자에게는 어떤 웹사이트가 제공되는지 리스트가 너무 길어서 식탁보에서 제공하는 사이트를 일목요연하게 보지 못할 것 같았습니다.
2. 그리드 형태로 분류/사이트를 보여주면, 분류를 클릭하여 분류 내에 속한 일부 사이트를 한 눈에 보고 바로 사이트에 접속할 수 있을 것 같습니다

뱅킹 분류 클릭 -> ㅇㅇ은행 로고 더블클릭이라는 UX가 마우스 이동이 적고 좋아보입니다

**Comment by rkttu** [comment]
#123 이슈로 병합합니다.

**Comment by rkttu** [comment]
1.9.0 출시로 이 이슈를 완전히 종결합니다.
