### ISSUE TITLE
[제안] 특정 은행에서 발생하는 버그에 관한 가이드 문서 작성

### ISSUE THREAD

**Issue by juyonLee00** [yourtablecloth/TableCloth#90]
#88 에 제시했던 버그에 대해 가이드 문서를 작성하는 이슈를 제안하고 싶습니다.

아래쪽에 관련 링크를 참조합니다.
_Originally posted by @level120 in https://github.com/yourtablecloth/TableCloth/issues/88#issuecomment-1221454987_

**Comment by juyonLee00** [comment]
이 이슈는 제가 개선하도록 하겠습니다

**Comment by rkttu** [comment]
@juyonLee00 다른 작업을 하다가 이 이슈를 같이 처리하게 되었습니다. https://github.com/yourtablecloth/yourtablecloth.github.io/blob/main/docs/troubleshoot.md 문서의 내용을 리뷰해주시고, 보충/개선할 내용이 있을 경우 PR 주시면 감사하겠습니다.

이 이슈는 우선 닫도록 하겠습니다.
