### ISSUE TITLE
[제안] 데이터테이블 검색 기능 혹은 안내 문장 수정

### ISSUE THREAD

**Issue by YOUNAVI** [yourtablecloth/TableCloth#99]
데이터테이블의 웹 사이트를 검색하는 기능에서 "신한" 과 같은 웹 사이트 이름으로 검색하는게 아닌 "뱅킹"이나 숫자 "5", 웹 사이트 주소로 검색해도 결과가 출력됩니다. 하지만 안내문에서는 찾고 싶은 웹 사이트 이름을 입력하라고 적혀있기에, 숫자는 검색 불가능하게 바꾸거나 안내문을 "찾고 싶은 웹 사이트의 이름이나 분류를 입력하세요" 라고 수정하는게 좋을 것 같습니다. 혹은 웹 사이트 이름과 분류로만 검색할 수 있게 바꾸는 것도 좋을 것 같습니다. 원래는 웹 사이트 데이터가 많고 분류가 몇 가지 안되기에 분류로 필터링하는 기능을 넣고자 했으나 검색 기능에서 분류도 검색이 가능하기에 필터링 기능이 아닌 해당 부분의 수정을 제안합니다. 수정이 필요할지, 하게 된다면 어떤 식으로 변경해야할지 논의했으면 좋겠습니다.

![image](https://user-images.githubusercontent.com/107922551/190599283-2472fec9-a3f3-427b-88e2-28c82c2cbfc4.png)
![image](https://user-images.githubusercontent.com/107922551/190599327-ad480f64-6b65-4c7e-aaa4-a7f522ac1a5a.png)

**Comment by rkttu** [comment]
0.5.6 버전에서 수정 사항을 반영하여 출시할 예정입니다.
